# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: Eeshooshohbiej5oot9Nee2PoeSooque8eeno8Oowai3weemuochei9ba9buuy1Yahmod9ooxei0Wievah1IiGhook1Sohth1iax6aerimei4Oosiek3cee7em0adohS

test:
  secret_key_base: IpheizooL9eighaezu3OhGai1aiho9Kieph0eemiw6taiyie5DaecafietahG7vuxootophoriHaekeu2waeroriThaPh0NieN0aediz5faimai2Jahthietaibei3ph

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
