# frozen_string_literal: true

module ICA
  # This is mainly so we can keep track of which card has already been persisted to the remote system
  class CardAccountMapping < ApplicationRecord
    belongs_to :customer_account_mapping, class_name: 'ICA::CustomerAccountMapping'
    has_one :garage_system, through: :customer_account_mapping

    validates :card_identifier, presence: true
    # Internal key, generated by our code to find card data
    validates :card_key, presence: true

    before_validation :generate_card_key, on: :create

    private

    def generate_card_key
      self.card_key ||= SecureRandom.uuid
    end
  end
end
